// =============================================================================
// THE BUYER PANEL BANK — sixty-odd personas, made from the twin's segments.
//
// The buyer panel the playbook bench used was five personas from one model.
// This makes a larger bank from the twin's seven segments (segments.ts): ten
// people a segment, each a variation the segment's own description allows —
// age, circumstance, how they would use a file, what they would pay (around
// the segment's stated top price), what they would use instead. They are
// TEST FIXTURES: generated, deterministic, and nobody real.
//
// SPLIT ONCE, HERE, AND NEVER AGAIN: three of each segment's ten go to the
// HELD-OUT set. The product-making code, the brains that stand in for its
// model, and their tests never read it (`the-held-out-panel-is-not-read`
// fails if anything but the judging harness names it). It exists so a product
// tuned on the working set can be judged by people it was not tuned on.
//
//   npx tsx tests/simulation/panel/generate-bank.mts
// =============================================================================
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { Rng, hashOf } from '../twin/rng.js';
import { SEGMENTS, THEMES } from '../twin/segments.js';

export interface Persona {
  id: string; segment: string; who: string; age: number; circumstance: string;
  format: 'paper' | 'fillable' | 'phone'; wtpDollars: number; freeAlternative: string;
  objection: string; needs: string[];
}

const CIRCUMSTANCES: Record<string, string[]> = {
  'after-a-loss': ['sorted out a parent\'s papers last year', 'is executor for an aunt', 'lost a spouse and is reorganising', 'watched a friend struggle after a death'],
  'young-family': ['has two children under five', 'is a single parent of a teenager', 'is expecting a second child', 'shares custody and two calendars'],
  caregiver: ['looks after a mother with dementia', 'shares care of a father with two siblings', 'manages a disabled brother\'s appointments', 'cares for a neighbour on weekdays'],
  'paper-keeper': ['keeps every statement in binders', 'moved into a smaller house last spring', 'has a daughter who keeps asking', 'is newly retired and organising'],
  skeptic: ['rents a flat with a roommate', 'builds spreadsheets for fun', 'has bought one PDF and regretted it', 'is twenty-six and owns very little'],
  'side-business': ['sells crafts at weekend markets', 'drives for a delivery app', 'tutors in the evenings', 'does bookkeeping for a cousin\'s cafe'],
  homeowner: ['bought a 1970s house last year', 'has a dog and two cats', 'lets a basement flat', 'is handy and does most repairs'],
};
const FREE = ['a notebook', 'a Google Doc', 'a spreadsheet template', 'their phone\'s notes app', 'a free printable from a blog', 'nothing at all'];
const OBJECTIONS = ['no reviews yet', 'not fillable on a tablet', 'too many pages that do not apply', 'could make one myself', 'unsure the seller is real', 'price is above what printables cost'];

const rows: Persona[] = [];
for (const s of SEGMENTS) {
  for (let i = 0; i < 10; i++) {
    const r = new Rng('persona', s.key, i);
    const age = s.key === 'paper-keeper' ? r.int(60, 82) : s.key === 'skeptic' ? r.int(22, 34) : r.int(28, 66);
    rows.push({
      id: `${s.key}-${String(i + 1).padStart(2, '0')}`, segment: s.key, who: s.who, age,
      circumstance: r.pick(CIRCUMSTANCES[s.key] ?? ['—']),
      format: r.pick(['paper', 'paper', 'fillable', 'phone'] as const),
      wtpDollars: Math.max(2, Math.round(s.wtpDollars * (0.6 + 0.8 * r.next()) * 2) / 2),
      freeAlternative: r.pick(FREE), objection: r.pick(OBJECTIONS),
      needs: s.themes.map((t) => THEMES[t].name),
    });
  }
}
// Three of each segment's ten, chosen by a hash of the id, never by order: every segment is in both sets.
const heldOut = SEGMENTS.flatMap((s) => rows.filter((p) => p.segment === s.key)
  .sort((a, b) => hashOf('held-out', a.id) - hashOf('held-out', b.id)).slice(0, 3));
const working = rows.filter((p) => !heldOut.includes(p));
const label = 'TEST FIXTURE: generated by tests/simulation/panel/generate-bank.mts from the twin\'s segments; nobody real.';
writeFileSync(resolve(import.meta.dirname, '../../fixtures/buyer-panel-bank/working.json'), `${JSON.stringify({ label, personas: working }, null, 1)}\n`);
writeFileSync(resolve(import.meta.dirname, '../../fixtures/buyer-panel-bank/held-out.json'), `${JSON.stringify({ label, personas: heldOut }, null, 1)}\n`);
process.stdout.write(`${String(rows.length)} personas: ${String(working.length)} working, ${String(heldOut.length)} held out\n`);
