// =============================================================================
// FOUNDRY — Money, as a place the owner stands in
//
// One address that answers one question: what of this is actually mine?
//
// Every figure on this page comes from `services/economy/projection.ts`, which
// is arithmetic over rows a provider wrote. Nothing here computes anything of
// its own, and nothing here is generated by a model. The page's whole job is to
// show the SUBTRACTION — what came in, and everything already spoken for —
// because the number people get wrong is never the revenue, it is what is left.
//
// THREE QUALITIES, DRAWN DIFFERENTLY. Measured, estimated, and not known. A
// figure that is not known is never drawn as a zero and never drawn in the same
// weight as one that is: "$0.00" and "not known" are different facts and the
// difference is the whole point of this surface.
//
// WHAT THE OWNER CAN DO HERE is exactly the three things that turn a "not
// known" into a number: record what he assumes about tax, set the floor he
// wants kept, and record money he has actually moved. Nothing else, because
// nothing else would be true.
// =============================================================================

import { Hono } from 'hono';
import { html, raw } from 'hono/html';
import type { HtmlEscapedString } from 'hono/utils/html';
import { page } from './foundry-shell.js';
import { ago, mark } from '../../views/owner/shell.js';
import type { Where } from './foundry-shell.js';
import { requireInstitutionOwner } from '../../middleware/rbac.js';
import { query } from '../../db/client.js';
import { record, setPolicy } from '../../services/economy/ledger.js';
import { EVALUATION_RULE, type Evaluation } from '../../services/capital/evaluation.js';
import { DECISION_RULE } from '../../services/capital/models.js';
import { FEE_VERSION } from '../../services/capital/fees.js';
import {
  CapitalRefused, beginObserving, capitalResearchReading, stopObserving, type LastWindow,
} from '../../services/capital/research.js';
import {
  distributableSurplus, dollars, figureText, grossCharged, ledgerEntries, moneyBanked,
  runningCost, unitContribution, type Figure,
} from '../../services/economy/projection.js';

export const moneyRoutes = new Hono();

type H = HtmlEscapedString | Promise<HtmlEscapedString>;

const frame: Where = {
  eyebrow: 'Economics',
  crumbs: [{ href: '/foundry', label: 'Foundry' }, { href: '/foundry/money', label: 'Economics' }],
  scope: { kind: 'foundry', id: null, name: 'Economics' }, local: [], chips: [],
};

async function founderOf(c: any): Promise<string | null> {
  const founder = c.get('founder') as { id?: string } | undefined;
  return founder?.id ? String(founder.id) : null;
}

/** A figure, with its quality visible rather than implied. */
const fig = (f: Figure): H => f.cents === null
  ? html`<span class="unknown">not known</span>`
  : html`<span>${dollars(f.cents)}${f.quality === 'estimated' ? html` <span class="quiet">estimated</span>` : ''}</span>`;

// A LINE OF THE SUBTRACTION IS A NUMBER, NOT A PARAGRAPH.
//
// Every figure here knows why it is what it is, and for a long time every one
// of them said so on the same screen: seven rows, seven reasons, six hundred
// words to carry six zeroes. The arithmetic — the thing the page exists to show
// — was the smallest part of it.
//
// The reason is not dropped, because a figure that cannot say where it came
// from is worse than no figure. It moves one tap down, with the others, so
// this surface answers "what is mine" at a glance and "why" on request. That
// is the difference between watching and inspecting, and it is the whole
// argument for keeping them apart.
const line = (label: string, f: Figure, negative = false): H => html`
  <div class="mline">
    <dt>${negative ? '− ' : ''}${label}</dt>
    <dd>${fig(f)}</dd>
  </div>`;

/** The reasons, together, behind one disclosure rather than seven. */
const reasons = (rows: Array<[string, Figure]>): H => html`
  <details class="why-money">
    <summary>Why each line is what it is</summary>
    <dl class="facts">
      ${rows.map(([label, f]) => html`<div><dt>${label}</dt><dd>${f.because}</dd></div>`)}
    </dl>
  </details>`;

moneyRoutes.get('/foundry/money', async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return c.redirect('/onboarding');
  const done = String(c.req.query('done') ?? '');
  const error = String(c.req.query('error') ?? '');

  const s = await distributableSurplus(founderId);
  const { obligationsFor } = await import('../../services/venture/obligations.js');
  const owedToBuyers = await obligationsFor(founderId);
  const gross = await grossCharged(founderId);
  const banked = await moneyBanked();

  const ledger = await ledgerEntries(founderId, 30);
  const cost = await runningCost(founderId);

  const sales = await query(
    `SELECT id, amount_cents, currency, status, created_at, provider, delivered_files_json, delivered_files_seen_at
       FROM experiment_fulfilments WHERE founder_id = ? ORDER BY created_at DESC LIMIT 25`,
    [founderId]);
  // WHO TOOK THE FEE, BY NAME (roadmap D4). Every sale read "Stripe took",
  // written when Stripe was the only way anything was paid; an Etsy sale's
  // fee is Etsy's.
  const providerName = (p: unknown): string => {
    const k = String(p ?? '').toLowerCase();
    return k === 'etsy' ? 'Etsy' : k === 'stripe' ? 'Stripe' : k ? k.charAt(0).toUpperCase() + k.slice(1) : 'The provider';
  };
  // AND WHAT THE MARGIN LEAVES OUT, said rather than silently omitted: what it
  // cost to be found beyond the provider's fees, and his own time, which he
  // enters in minutes (D6) and which has no price here.
  // WHICH FILE EACH VENUE BUYER RECEIVED (migration 363), or that it is not
  // known. A Stripe sale's deliverable is the test's own material, sent by mail.
  const deliveredLine = (row: Record<string, unknown>): string | null => {
    if (String(row.provider ?? '').toLowerCase() === 'stripe') return null;
    if (row.delivered_files_json == null) return 'which file this buyer received is not known';
    const files = JSON.parse(String(row.delivered_files_json)) as Array<{ filename: string; sizeBytes: number | null }>;
    const on = String(row.delivered_files_seen_at ?? '').slice(0, 10);
    const who = providerName(row.provider);
    return files.length === 0 ? `${who} held no file on the listing when this sold (read ${on})`
      : `delivered ${files.map((f) => `${f.filename} (${f.sizeBytes === null ? 'size not given' : `${f.sizeBytes.toLocaleString('en-US')} bytes`}`).join(', ')}, as ${who} held it on ${on})`;
  };
  const minutes = Number(((await query(
    `SELECT COALESCE(SUM(minutes), 0) AS n FROM owner_minutes WHERE founder_id = ? AND withdrawn_at IS NULL`, [founderId]))
    .rows[0] as Record<string, unknown>).n ?? 0);
  const notCounted = 'Not counted in what was left: what it cost to be found beyond the provider\'s own fees '
    + '(advertising, listing renewals not on the receipt), and your own time'
    + (minutes > 0 ? `: ${String(minutes)} minutes entered on your tests; no price is put on it here.`
      : ', which is not entered — the minutes you spend on a test can be entered on its page; no price is put on it here.');
  const units = await Promise.all(sales.rows.map(async (r) => {
    const row = r as Record<string, unknown>;
    return { row, view: await unitContribution(founderId, String(row.id)) };
  }));

  const notice = error
    ? html`<p class="noticed" role="alert"><strong>That did not go through.</strong> ${error}</p>`
    : done === 'tax' ? html`<p class="noticed">Recorded. It is still an estimate, and it still says so.</p>`
      : done === 'floor' ? html`<p class="noticed">Recorded. That much is kept back before anything is called yours.</p>`
        : done === 'moved' ? html`<p class="noticed">Recorded. That is measured now, because you saw it happen.</p>` : '';

  // THE FIGURES FIRST, AS INSTRUMENTS. Five tiles read from the same
  // subtraction the page has always shown — what is held, what is reserved
  // for tax, the floor, what could be asked back, and what is his — each
  // drawn with its quality visible. Then the subtraction itself, then how
  // money moved, then everything that grounds a figure, one fold down.
  const tile = (name: string, label: string, f: Figure, detail: string, cls = '') => html`<div class="tile${cls}"><dt class="k">${mark(name)}${label}</dt>
      <dd class="v">${f.cents === null ? html`<span class="unknown">not known</span>` : html`${dollars(f.cents)}${f.quality === 'estimated' ? html` <span class="dim">est.</span>` : ''}`}</dd>
      <dd class="d">${detail}</dd></div>`;
  // Movement over thirty days, drawn only from rows and only as a trend when
  // there are three days with movement; otherwise the honest absence.
  const { sparkline } = await import('../../lib/sparkline.js');
  const since = Date.now() - 30 * 86_400_000;
  const recent = ledger.filter((e) => new Date(e.occurredAt.replace(' ', 'T')).getTime() >= since);
  const inCents = recent.filter((e) => e.direction === 'in').reduce((t, e) => t + e.amountCents, 0);
  const outCents = recent.filter((e) => e.direction === 'out').reduce((t, e) => t + e.amountCents, 0);
  const byDay = new Map<string, number>();
  for (const e of [...recent].sort((a, b) => (a.occurredAt < b.occurredAt ? -1 : 1))) {
    const d = e.occurredAt.slice(0, 10);
    byDay.set(d, (byDay.get(d) ?? 0) + (e.direction === 'in' ? e.amountCents : -e.amountCents));
  }
  let running = 0;
  const spark = sparkline([...byDay.values()].map((v) => { running += v; return running; }), { width: 320, height: 64, meaning: 'up_is_good' });
  const KIND_MARK = (e: typeof ledger[number]): string => e.direction === 'in' ? 'money' : /tax/.test(e.kind) ? 'reserve' : /owner/.test(e.kind) ? 'owner' : 'cash';
  const fold = (id: string, title: string, gist: string, inner: H) =>
    html`<details class="fold" id="${id}"><summary><h2>${title}</h2><span class="gist">${gist}</span></summary>${inner}</details>`;
  const body = html`
    <h1>Economics</h1>
    ${notice}
    <p class="lede">${s.sentence}</p>

    <dl class="glance eco-glance" aria-label="The money, at a glance">
      ${tile('cash', 'Held by the providers, ours', s.held, 'settled with the provider; not a bank balance')}
      ${tile('reserve', 'Held for tax', s.taxReserve, s.taxReserve.policy ? 'from the assumption you recorded' : 'no assumption recorded yet')}
      ${tile('reserve', 'Kept to keep running', s.operatingReserve, 'the floor you set')}
      ${tile('warn', 'Could be asked back', s.refundExposure, 'refund exposure on delivered work')}
      ${tile('owner', 'Yours to take', s.figure, s.figure.cents !== null && s.figure.cents < 0 ? 'more is spoken for than is held' : 'after everything already spoken for', ' yours')}
    </dl>

    <div class="know">
      <h2>The subtraction</h2>
      <dl class="facts money">
        ${line('Held by the providers, ours', s.held)}
        ${line('Paid for, not delivered', s.obligations, true)}
        ${line('Could be asked back', s.refundExposure, true)}
        ${line('Held for tax', s.taxReserve, true)}
        ${line('Kept to keep running', s.operatingReserve, true)}
        ${line('Already authorised to spend', s.authorisedCapital, true)}
        <div class="mline total">
          <dt>Yours to take</dt>
          <dd>${fig(s.figure)}</dd>
        </div>
      </dl>
      ${owedToBuyers.length ? html`<h2>Owed to buyers</h2>
      <ul class="owed-to-buyers">${owedToBuyers.map((o) => html`<li><a href="/foundry/experiments/${o.experimentId}">${o.sentence}</a>${o.asksHim ? html` <strong>${o.asksHim}</strong>` : ''}</li>`)}</ul>` : ''}
      ${reasons([
    ['Held by the providers, ours', s.held],
    ['Paid for, not delivered', s.obligations],
    ['Could be asked back', s.refundExposure],
    ['Held for tax', s.taxReserve],
    ['Kept to keep running', s.operatingReserve],
    ['Already authorised to spend', s.authorisedCapital],
    ['Yours to take', s.figure],
  ])}
    </div>

    <section class="panel trend eco-trend" aria-label="Money movement, thirty days">
      <header><h2>${mark('cash')}Movement <span class="dim">30 days</span></h2></header>
      ${spark.svg ? html`<div class="chart">${raw(spark.svg)}</div>` : ''}
      <p class="figures"><span class="up">+${dollars(inCents)} in</span><span class="down">−${dollars(outCents)} out</span>
        ${recent.length === 0 ? html`<span class="quiet">nothing has moved yet; the first row will be written from the provider's own record, not by me</span>`
    : spark.svg ? '' : html`<span class="quiet">${String(byDay.size)} ${byDay.size === 1 ? 'day' : 'days'} with movement — not yet a trend</span>`}</p>
    </section>

    <section class="panel ledger-panel" aria-label="The ledger">
      <header><h2>${mark('changed')}Economic events</h2><span class="dim">${ledger.length ? `${String(ledger.length)} newest, in the order the world put them` : ''}</span></header>
      ${ledger.length === 0
        ? html`<p class="quiet">Nothing yet. The first row will be written from the provider's own record, not by me.</p>`
        : html`<ul class="ledger">${ledger.map((e) => html`<li class="${e.direction}">
            ${mark(KIND_MARK(e))}
            <span class="what">${e.whatItIs}${e.quality === 'estimated' ? html` <span class="pill warn">estimated</span>` : ''}</span>
            <span class="amt">${e.direction === 'out' ? '−' : '+'}${dollars(e.amountCents)}</span>
            <span class="when"><time>${ago(e.occurredAt)}</time> · ${e.provider}${e.fromEvent ? ` event ${e.fromEvent}` : ` ${e.providerRef}`}</span>
            <details class="why-row"><summary class="quiet">why</summary><p class="quiet">${e.because}${e.assumption ? ` Assuming: ${e.assumption}.` : ''}</p></details>
          </li>`)}</ul>`}
    </section>

    <div class="inspect">
    ${fold('cannot', 'What I cannot tell you', `reached a bank: ${figureText(banked)}`, html`
      <p><strong>What has reached a bank: ${fig(banked)}.</strong> ${banked.because}</p>
      <p class="quiet">Gross charged, before the providers took anything: ${figureText(gross)}. That number is
        not yours and is only here so the subtraction above can be checked against it.</p>`)}

    ${fold('sales', 'Every sale, and what was left of it', units.length ? `${String(units.length)} ${units.length === 1 ? 'sale' : 'sales'}` : 'none yet', units.length === 0
        ? html`<p class="quiet">Nothing has been sold. When something is, each sale appears here with
            what the provider took out of it, so the margin is never guessed at from the price.</p>`
        : html`<ul class="sales">${units.map(({ row, view }) => html`<li>
            <b>${dollars(Number(row.amount_cents))}</b> ${String(row.status)}
            · ${providerName(row.provider)} took ${fig(view.providerFee)}
            ${deliveredLine(row as Record<string, unknown>) ? html`<br /><small class="quiet">${deliveredLine(row as Record<string, unknown>)}</small>` : ''}
            · left ${fig(view.contribution)}
            ${view.contribution.cents === null
              ? html`<p class="quiet">${view.contribution.because}</p>` : ''}
          </li>`)}</ul>
          <p class="quiet">${notCounted}</p>`)}

    ${fold('cost', 'What running this has cost', figureText(cost.total), html`
      <p><strong>${fig(cost.total)}</strong> ${cost.total.because}</p>
      <p class="quiet">Not part of the subtraction above. This money has already left, out of your own
        pocket rather than out of anything a buyer paid — subtracting it there would count it twice
        the moment you record having put money in.</p>
      ${cost.recent.length === 0 ? '' : html`<ul class="sales">${cost.recent.map((l) => html`<li>
          <b>${dollars(l.amountCents)}</b> on ${l.tool}${l.capability ? ` (${l.capability})` : ''}
          · ${l.source}${l.providerRef ? ` · receipt ${l.providerRef}` : ''}
          · ${l.at}
        </li>`)}</ul>`}`)}

    <p class="quiet" id="trading-research">Trading research is a simulation and is never counted here:
      <a href="/foundry/money/research">what it has found</a>.</p>

    ${fold('set', 'What you can set', 'tax, the floor, money you moved', html`
      <h3>Tax</h3>
      <p class="quiet">An assumption of yours, applied to a measured basis, so money you may owe is
        not money you think you can take. It is never a filing, a return, or advice, and it will
        keep saying "estimated" wherever it appears.</p>
      <form class="inline" method="POST" action="/foundry/money/tax">
        <label class="sr" for="rate">Percentage to hold back</label>
        <input id="rate" name="rate" type="text" inputmode="decimal" placeholder="e.g. 30" />
        <label class="sr" for="basis">What it applies to</label>
        <select id="basis" name="basis">
          <option value="contribution">of contribution</option>
          <option value="gross_receipts">of gross receipts</option>
        </select>
        <label class="sr" for="taxsource">Where this comes from</label>
        <input id="taxsource" name="source" type="text" placeholder="Where this number comes from, in your words" />
        <button class="btn" type="submit">Record it</button>
      </form>

      <h3>The floor</h3>
      <p class="quiet">What stays in the account no matter what the arithmetic says.</p>
      <form class="inline" method="POST" action="/foundry/money/floor">
        <label class="sr" for="floor">Amount to keep</label>
        <input id="floor" name="amount" type="text" inputmode="decimal" placeholder="e.g. 500" />
        <label class="sr" for="floorwhy">Why</label>
        <input id="floorwhy" name="source" type="text" placeholder="Why that much" />
        <button class="btn" type="submit">Record it</button>
      </form>

      <h3>Money you moved</h3>
      <p class="quiet">A payout from this Stripe account mixes the land sales and AcreOS with this,
        so I will not read one as yours. What you actually moved, you can tell me, and then it is
        measured.</p>
      <form class="inline" method="POST" action="/foundry/money/moved">
        <label class="sr" for="amount">Amount</label>
        <input id="amount" name="amount" type="text" inputmode="decimal" placeholder="e.g. 250" />
        <label class="sr" for="direction">Direction</label>
        <select id="direction" name="direction">
          <option value="owner_distribution">I took out</option>
          <option value="owner_contribution">I put in</option>
        </select>
        <label class="sr" for="movedwhy">What it was</label>
        <input id="movedwhy" name="because" type="text" placeholder="What it was" />
        <button class="btn" type="submit">Record it</button>
      </form>
      <p class="quiet">Nothing here is deleted. A row you did not mean is corrected by recording the opposite movement, with the reason, so the ledger shows both what was said and what was corrected.</p>`)}
    </div>`;
  return c.html(page('Economics', body, 'money', frame));
});

// ─── What the owner sets ─────────────────────────────────────────────────────

const back = (c: any, ok: string, err?: string) =>
  c.redirect(`/foundry/money?${err ? `error=${encodeURIComponent(err)}` : `done=${ok}`}`);

/** "30" and "30%" and "30.5" all mean the same thing to a person. */
function basisPoints(raw: string): number | null {
  const n = Number(String(raw).replace('%', '').trim());
  if (!Number.isFinite(n) || n < 0 || n > 100) return null;
  return Math.round(n * 100);
}

/** Dollars as typed, to whole cents. Refuses what it cannot read. */
function cents(raw: string): number | null {
  const n = Number(String(raw).replace(/[$,]/g, '').trim());
  if (!Number.isFinite(n) || n < 0) return null;
  return Math.round(n * 100);
}

moneyRoutes.post('/foundry/money/tax', requireInstitutionOwner(), async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return back(c, '', 'No owner on this request.');
  const form = await c.req.parseBody();
  const bps = basisPoints(String(form.rate ?? ''));
  const source = String(form.source ?? '').trim();
  if (bps === null) return back(c, '', 'That rate is not a percentage between 0 and 100.');
  if (!source) return back(c, '', 'An estimate has to say where it came from, or nobody can check it.');
  const basis = String(form.basis) === 'gross_receipts' ? 'gross_receipts' as const : 'contribution' as const;
  await setPolicy({
    founderId, kind: 'tax_reserve', rateBps: bps, basis, source,
    because: 'The owner recorded what he assumes he will owe, so that money is held back rather than counted as his.',
    setBy: 'owner',
  });
  return back(c, 'tax');
});

moneyRoutes.post('/foundry/money/floor', requireInstitutionOwner(), async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return back(c, '', 'No owner on this request.');
  const form = await c.req.parseBody();
  const amount = cents(String(form.amount ?? ''));
  const source = String(form.source ?? '').trim();
  if (amount === null) return back(c, '', 'That amount is not a number of dollars.');
  if (!source) return back(c, '', 'Say why that much, so the floor can be argued with later.');
  await setPolicy({
    founderId, kind: 'operating_reserve', amountCents: amount, source,
    because: 'The owner set a floor that stays in the account before anything is called his.',
    setBy: 'owner',
  });
  return back(c, 'floor');
});

moneyRoutes.post('/foundry/money/moved', requireInstitutionOwner(), async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return back(c, '', 'No owner on this request.');
  const form = await c.req.parseBody();
  const amount = cents(String(form.amount ?? ''));
  const because = String(form.because ?? '').trim();
  // A WORD IT DOES NOT KNOW IS NOT "TOOK OUT". This read anything that was
  // not `owner_contribution` as a distribution, so a mistyped direction —
  // or a form posted by hand — silently wrote money OUT of the institution
  // and answered "done". The ledger has no delete by design, so a wrong row
  // is corrected by a second row and never erased: a write that guesses what
  // the owner meant is a permanent mark on the one figure he trusts.
  const said = String(form.direction ?? '');
  if (said !== 'owner_contribution' && said !== 'owner_distribution') {
    return back(c, '', `"${said || 'nothing'}" is not a direction I know. Say whether you put money in or took it out; I will not guess, because the ledger keeps what it is told.`);
  }
  const direction = said;
  if (amount === null || amount === 0) return back(c, '', 'That amount is not a number of dollars.');
  // AN AMOUNT A PERSON DID NOT MEAN. A million dollars through this form is
  // far likelier to be a slip than a fact, and the row cannot be taken back.
  if (amount < 0) return back(c, '', 'Record what moved as a positive amount, and say which way it went.');
  if (amount > 100_000_00) return back(c, '', `$${(amount / 100).toFixed(2)} is more than this form will take in one entry. If that is really the figure, record it in parts, so a slipped key cannot become the ledger.`);
  if (!because) return back(c, '', 'Say what the movement was, so the ledger reads as something rather than as an adjustment.');
  await record({
    founderId,
    kind: direction,
    amountCents: amount,
    occurredAt: new Date(),
    // NOT 'stripe'. The owner saying he moved money is a different kind of
    // evidence from Stripe saying so, and the provider column is what a
    // reconciler would use to ask the other side. `owner` is the other side.
    provider: 'owner',
    providerRef: `${direction}:${Date.now()}`,
    claimQuality: 'measured',
    evidenceMode: 'real',
    because,
  });
  return back(c, 'moved');
});

// =============================================================================
// TRADING RESEARCH, as the owner reads it (/foundry/money/research; migration
// 364). A reading under Economics, not a new door, and deliberately not a
// trading dashboard: no ticker tape, no P&L in green, nothing that rewards
// activity. It says what question is being asked, what the evidence says so
// far, what the research cannot see, and that no order is possible. A
// simulated result is always called simulated, and none of it is counted in
// the figures above.
// =============================================================================
const researchFrame: Where = {
  eyebrow: 'Economics',
  crumbs: [{ href: '/foundry', label: 'Foundry' }, { href: '/foundry/money', label: 'Economics' },
    { href: '/foundry/money/research', label: 'Trading research' }],
  scope: { kind: 'foundry', id: null, name: 'Trading research' }, local: [], chips: [],
};

const researchBack = (c: any, ok: string, err?: string) =>
  c.redirect(`/foundry/money/research?${err ? `error=${encodeURIComponent(err)}` : `done=${ok}`}`);
const researchDay = (iso: string): string => iso.slice(0, 16).replace('T', ' ');
const usd = (x: number): string => `${x < 0 ? '−' : ''}$${Math.abs(x).toFixed(2)}`;

const VERDICT_WORDS: Record<string, string> = {
  insufficient_evidence: 'Not enough yet',
  market_is_better: 'The market is better — do not trade',
  no_net_edge: 'No edge after costs — do not trade',
  survived_holdout_owner_review: 'Survived the test — yours to review, not to trade',
};

function verdictPanel(e: { computedAt: string; verdict: string; digest: string; resolvedCount: number; result: Evaluation }): H {
  const r = e.result;
  return html`<section class="know" id="verdict">
    <h2>What the evidence says</h2>
    <p><strong>${VERDICT_WORDS[e.verdict] ?? e.verdict}.</strong> ${r.sentence}</p>
    <dl class="facts">
      <div><dt>Resolved markets</dt><dd>${String(e.resolvedCount)} of the ${String(EVALUATION_RULE.minResolvedMarkets)} fixed in advance</dd></div>
      <div><dt>Forecast error (Brier, lower is better)</dt><dd>${r.brier.model === null ? 'not known' : `model ${r.brier.model.toFixed(4)}`}
        · ${r.brier.market === null ? 'market not known' : `market ${r.brier.market.toFixed(4)}`}
        ${r.brier.pairs > 1 && r.brier.diffLow !== null && r.brier.diffHigh !== null
    ? ` · difference ${r.brier.pairedDiff!.toFixed(4)} (95%: ${r.brier.diffLow.toFixed(4)} to ${r.brier.diffHigh.toFixed(4)}) over ${String(r.brier.pairs)} markets` : ''}</dd></div>
      <div><dt>Simulated result — never money</dt><dd>${String(r.simulated.trades)} simulated trades of ${String(DECISION_RULE.contracts)} contracts:
        ${usd(r.simulated.netDollars)} at the displayed book, ${usd(r.simulated.netDollarsAdverse)} with one cent worse per contract;
        worst fall ${usd(r.simulated.maxDrawdown)}${r.simulated.unfilled ? `; ${String(r.simulated.unfilled)} could not fill at all` : ''}</dd></div>
      <div><dt>Left out, and why</dt><dd>${String(r.excluded.ruleChanged)} with a changed rule · ${String(r.excluded.noModelProbability)} with no model forecast ·
        ${String(r.excluded.feeUnknown)} with an unknown fee · ${String(r.excluded.fillNotReproduced ?? 0)} whose fill did not reproduce from its book</dd></div>
      <div><dt>Read</dt><dd>${researchDay(e.computedAt)} · digest ${e.digest.slice(0, 12)}</dd></div>
    </dl>
  </section>`;
}

const MODEL_WORDS: Record<string, string> = { market_implied_v1: 'The market\'s own price', proxy_drift_v1: 'The proxy model' };

function lastWindowPanel(w: LastWindow): H {
  const p = (x: number | null): string => (x === null ? 'not known' : x.toFixed(4));
  return html`<section class="know" id="last-window">
    <h2>The last window</h2>
    <p class="quiet">${w.marketTicker}, read ${researchDay(w.receivedAt)}, closing ${researchDay(w.closeTime)}.</p>
    <dl class="facts">
      <div><dt>Reference level</dt><dd>${w.floorStrike === null ? 'not yet published' : `$${w.floorStrike.toFixed(2)}`}</dd></div>
      <div><dt>YES bid / ask</dt><dd>${p(w.yesBid)} / ${p(w.yesAsk)}</dd></div>
      <div><dt>Proxy (not the settlement source)</dt><dd>${w.proxy ? `$${w.proxy.price.toFixed(2)} from ${w.proxy.source} at ${researchDay(w.proxy.observedAt)}${w.proxy.sigma1m === null ? '' : `; one-minute volatility ${(w.proxy.sigma1m * 100).toFixed(3)}%`}` : 'could not be read'}</dd></div>
      ${w.forecasts.map((f) => html`<div><dt>${MODEL_WORDS[f.model] ?? f.model}</dt><dd>P(YES) ${p(f.pYes)} — ${f.decision === 'skip' ? 'no trade' : `simulated ${f.decision.toUpperCase()}`}: ${f.reason}</dd></div>`)}
      ${w.fill ? html`<div><dt>Simulated fill — not a trade</dt><dd>${String(w.fill.filled)} of ${String(w.fill.requested)} ${w.fill.side.toUpperCase()} for ${usd(w.fill.cost)},
        fee ${w.fill.fee === null ? 'not known' : usd(w.fill.fee)} (${w.fill.feeVersion})</dd></div>` : ''}
    </dl>
  </section>`;
}

moneyRoutes.get('/foundry/money/research', async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return c.redirect('/onboarding');
  const done = String(c.req.query('done') ?? ''); const error = String(c.req.query('error') ?? '');
  const r = await capitalResearchReading(founderId);
  const observing = r.thesis?.status === 'observing';

  const body = html`
    ${done ? html`<p class="noticed" role="status">${done === 'begun' ? 'Observing. The first forecast is sealed at the next window.' : 'Stopped. What was recorded stays.'}</p>` : ''}
    ${error ? html`<p class="noticed" role="alert">${error}</p>` : ''}
    <section class="know" id="what">
      <h2>${observing ? 'Observing Kalshi\'s 15-minute Bitcoin contracts' : r.thesis ? 'Stopped' : 'Not observing anything'}</h2>
      <p>No order is possible. Foundry holds no exchange credential, and nothing in it can place, change or cancel one.
        This reads public prices, seals a forecast before each window closes, and scores it against the exchange's official result.
        Nothing here is income, and none of it is counted in Economics.</p>
      ${r.thesis ? html`<dl class="facts">
        <div><dt>The question</dt><dd>${r.thesis.hypothesis}</dd></div>
        <div><dt>What would prove it wrong</dt><dd>${r.thesis.falsifier}</dd></div>
        <div><dt>The alternative</dt><dd>${r.thesis.alternativeUse}</dd></div>
        <div><dt>${observing ? 'Since' : 'Ran'}</dt><dd>${r.thesis.begunByOwner ? 'Begun by you, ' : ''}${researchDay(r.thesis.begunAt)}${r.thesis.stoppedAt ? ` to ${researchDay(r.thesis.stoppedAt)} — ${r.thesis.stoppedBecause ?? ''}` : ''}</dd></div>
      </dl>` : ''}
    </section>

    ${r.evaluation ? verdictPanel(r.evaluation) : r.thesis ? html`<section class="know" id="verdict"><h2>What the evidence says</h2>
      <p>Nothing yet: the first evaluation is read each morning once results exist.</p></section>` : ''}

    ${r.thesis ? html`<section class="know" id="seen">
      <h2>What it has seen</h2>
      <p>${String(r.counts.snapshots)} windows observed, ${String(r.counts.resolved)} with the official result, ${String(r.counts.forecasts)} forecasts sealed,
        ${String(r.counts.simulatedFills)} simulated fills${r.counts.proxyMissing ? `, ${String(r.counts.proxyMissing)} windows where the proxy could not be read` : ''}.
        ${r.lastSnapshotAt ? `Last observed ${researchDay(r.lastSnapshotAt)}.` : ''}</p>
    </section>` : ''}

    ${r.lastWindow ? lastWindowPanel(r.lastWindow) : ''}

    <section class="know" id="rule">
      <h2>What decides these contracts</h2>
      ${r.rules ? html`<p>Settled on <strong>${r.rules.settlementSource}</strong>, as the exchange states it${r.rules.settlementNote ? html`: ${r.rules.settlementNote.replace(/\*\*/g, '')}` : '.'}</p>
        <p class="quiet">Fee rule as published: ${r.rules.feeType ?? 'not stated'}${r.rules.feeMultiplier === null ? '' : `, multiplier ${String(r.rules.feeMultiplier)}`}; first read ${researchDay(r.rules.firstSeenAt)}.</p>`
    : html`<p class="quiet">Not read yet.</p>`}
      ${r.latestRule ? html`<p class="quiet">The latest rule, in the exchange's words: ${r.latestRule}</p>` : ''}
    </section>

    <section class="know" id="blind">
      <h2>What this cannot see</h2>
      <ul class="plain">
        <li>The settlement index itself. It is licensed data; the model uses a public spot price as a proxy, and the gap between them is unknown.</li>
        <li>Whether a real order would fill. A simulated fill takes the displayed book at one instant, with no queue and no delay; one cent worse is shown beside it.</li>
        <li>The fee schedule as published. The formula (${FEE_VERSION}) is the handoff's reading; Kalshi's page refused this environment.</li>
        <li>Anything before ${String(EVALUATION_RULE.minResolvedMarkets)} results. Until then it says nothing, and it never says "trade".</li>
      </ul>
    </section>

    <section class="know" id="legacy">
      <h2>The old trading code</h2>
      <p>kalshi-genius and the old Apex Micro trading platform were read line by line (docs/foundry-institution/capital/LEGACY_TRADING_AUDIT.md).
        Neither showed an edge. The old paper results were wrong by construction: a comparison that could never say "up",
        a sizer that bet 30% at any forecast, a probability curve off by up to 3.7 points, and order paths that recorded fills that never happened.
        Nothing from either runs here; what was sound was rebuilt and tested.</p>
    </section>

    <section class="know" id="yours">
      <h2>Yours</h2>
      ${observing ? html`<form class="inline" method="POST" action="/foundry/money/research/stop">
          <label class="sr" for="because">Why stop</label>
          <input id="because" name="because" type="text" placeholder="Why stop, in your words" />
          <button class="btn" type="submit">Stop observing</button>
        </form>`
    : html`<form class="inline" method="POST" action="/foundry/money/research/begin">
          <button class="btn" type="submit">${r.thesis ? 'Begin a new observation' : 'Begin observing'}</button>
        </form>
        <p class="quiet">Costs nothing and risks nothing: public data only, about one read a minute.</p>`}
    </section>`;
  return c.html(page('Trading research', body, 'money', researchFrame));
});

moneyRoutes.post('/foundry/money/research/begin', requireInstitutionOwner(), async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return researchBack(c, '', 'No owner on this request.');
  try { await beginObserving(founderId); } catch (err) {
    if (err instanceof CapitalRefused) return researchBack(c, '', err.message);
    throw err;
  }
  return researchBack(c, 'begun');
});

moneyRoutes.post('/foundry/money/research/stop', requireInstitutionOwner(), async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return researchBack(c, '', 'No owner on this request.');
  const form = await c.req.parseBody();
  try {
    if (!(await stopObserving(founderId, String(form.because ?? '')))) return researchBack(c, '', 'Nothing was being observed.');
  } catch (err) {
    if (err instanceof CapitalRefused) return researchBack(c, '', 'Say why, so the record can be read later.');
    throw err;
  }
  return researchBack(c, 'stopped');
});
