// =============================================================================
// FOUNDRY — Money, as a place the owner stands in
//
// One address that answers one question: what of this is actually mine?
//
// Every figure on this page comes from `services/economy/projection.ts`, which
// is arithmetic over rows a provider wrote. Nothing here computes anything of
// its own, and nothing here is generated by a model. The page's whole job is to
// show the SUBTRACTION — what came in, and everything already spoken for —
// because the number people get wrong is never the revenue, it is what is left.
//
// THREE QUALITIES, DRAWN DIFFERENTLY. Measured, estimated, and not known. A
// figure that is not known is never drawn as a zero and never drawn in the same
// weight as one that is: "$0.00" and "not known" are different facts and the
// difference is the whole point of this surface.
//
// WHAT THE OWNER CAN DO HERE is exactly the three things that turn a "not
// known" into a number: record what he assumes about tax, set the floor he
// wants kept, and record money he has actually moved. Nothing else, because
// nothing else would be true.
// =============================================================================

import { Hono } from 'hono';
import { html, raw } from 'hono/html';
import type { HtmlEscapedString } from 'hono/utils/html';
import { page } from './foundry-shell.js';
import { ago, mark } from '../../views/owner/shell.js';
import type { Where } from './foundry-shell.js';
import { requireInstitutionOwner } from '../../middleware/rbac.js';
import { query } from '../../db/client.js';
import { record, setPolicy } from '../../services/economy/ledger.js';
import {
  distributableSurplus, dollars, figureText, grossCharged, ledgerEntries, moneyBanked,
  runningCost, unitContribution, type Figure,
} from '../../services/economy/projection.js';

export const moneyRoutes = new Hono();

type H = HtmlEscapedString | Promise<HtmlEscapedString>;

const frame: Where = {
  eyebrow: 'Economics',
  crumbs: [{ href: '/foundry', label: 'Foundry' }, { href: '/foundry/money', label: 'Economics' }],
  scope: { kind: 'foundry', id: null, name: 'Economics' }, local: [], chips: [],
};

async function founderOf(c: any): Promise<string | null> {
  const founder = c.get('founder') as { id?: string } | undefined;
  return founder?.id ? String(founder.id) : null;
}

/** A figure, with its quality visible rather than implied. */
const fig = (f: Figure): H => f.cents === null
  ? html`<span class="unknown">not known</span>`
  : html`<span>${dollars(f.cents)}${f.quality === 'estimated' ? html` <span class="quiet">estimated</span>` : ''}</span>`;

// A LINE OF THE SUBTRACTION IS A NUMBER, NOT A PARAGRAPH.
//
// Every figure here knows why it is what it is, and for a long time every one
// of them said so on the same screen: seven rows, seven reasons, six hundred
// words to carry six zeroes. The arithmetic — the thing the page exists to show
// — was the smallest part of it.
//
// The reason is not dropped, because a figure that cannot say where it came
// from is worse than no figure. It moves one tap down, with the others, so
// this surface answers "what is mine" at a glance and "why" on request. That
// is the difference between watching and inspecting, and it is the whole
// argument for keeping them apart.
const line = (label: string, f: Figure, negative = false): H => html`
  <div class="mline">
    <dt>${negative ? '− ' : ''}${label}</dt>
    <dd>${fig(f)}</dd>
  </div>`;

/** The reasons, together, behind one disclosure rather than seven. */
const reasons = (rows: Array<[string, Figure]>): H => html`
  <details class="why-money">
    <summary>Why each line is what it is</summary>
    <dl class="facts">
      ${rows.map(([label, f]) => html`<div><dt>${label}</dt><dd>${f.because}</dd></div>`)}
    </dl>
  </details>`;

moneyRoutes.get('/foundry/money', async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return c.redirect('/onboarding');
  const done = String(c.req.query('done') ?? '');
  const error = String(c.req.query('error') ?? '');

  const s = await distributableSurplus(founderId);
  const { obligationsFor } = await import('../../services/venture/obligations.js');
  const owedToBuyers = await obligationsFor(founderId);
  const gross = await grossCharged(founderId);
  const banked = await moneyBanked();

  const ledger = await ledgerEntries(founderId, 30);
  const cost = await runningCost(founderId);

  const sales = await query(
    `SELECT id, amount_cents, currency, status, created_at
       FROM experiment_fulfilments WHERE founder_id = ? ORDER BY created_at DESC LIMIT 25`,
    [founderId]);
  const units = await Promise.all(sales.rows.map(async (r) => {
    const row = r as Record<string, unknown>;
    return { row, view: await unitContribution(founderId, String(row.id)) };
  }));

  const notice = error
    ? html`<p class="noticed" role="alert"><strong>That did not go through.</strong> ${error}</p>`
    : done === 'tax' ? html`<p class="noticed">Recorded. It is still an estimate, and it still says so.</p>`
      : done === 'floor' ? html`<p class="noticed">Recorded. That much is kept back before anything is called yours.</p>`
        : done === 'moved' ? html`<p class="noticed">Recorded. That is measured now, because you saw it happen.</p>` : '';

  // THE FIGURES FIRST, AS INSTRUMENTS. Five tiles read from the same
  // subtraction the page has always shown — what is held, what is reserved
  // for tax, the floor, what could be asked back, and what is his — each
  // drawn with its quality visible. Then the subtraction itself, then how
  // money moved, then everything that grounds a figure, one fold down.
  const tile = (name: string, label: string, f: Figure, detail: string, cls = '') => html`<div class="tile${cls}"><dt class="k">${mark(name)}${label}</dt>
      <dd class="v">${f.cents === null ? html`<span class="unknown">not known</span>` : html`${dollars(f.cents)}${f.quality === 'estimated' ? html` <span class="dim">est.</span>` : ''}`}</dd>
      <dd class="d">${detail}</dd></div>`;
  // Movement over thirty days, drawn only from rows and only as a trend when
  // there are three days with movement; otherwise the honest absence.
  const { sparkline } = await import('../../lib/sparkline.js');
  const since = Date.now() - 30 * 86_400_000;
  const recent = ledger.filter((e) => new Date(e.occurredAt.replace(' ', 'T')).getTime() >= since);
  const inCents = recent.filter((e) => e.direction === 'in').reduce((t, e) => t + e.amountCents, 0);
  const outCents = recent.filter((e) => e.direction === 'out').reduce((t, e) => t + e.amountCents, 0);
  const byDay = new Map<string, number>();
  for (const e of [...recent].sort((a, b) => (a.occurredAt < b.occurredAt ? -1 : 1))) {
    const d = e.occurredAt.slice(0, 10);
    byDay.set(d, (byDay.get(d) ?? 0) + (e.direction === 'in' ? e.amountCents : -e.amountCents));
  }
  let running = 0;
  const spark = sparkline([...byDay.values()].map((v) => { running += v; return running; }), { width: 320, height: 64, meaning: 'up_is_good' });
  const KIND_MARK = (e: typeof ledger[number]): string => e.direction === 'in' ? 'money' : /tax/.test(e.kind) ? 'reserve' : /owner/.test(e.kind) ? 'owner' : 'cash';
  const fold = (id: string, title: string, gist: string, inner: H) =>
    html`<details class="fold" id="${id}"><summary><h2>${title}</h2><span class="gist">${gist}</span></summary>${inner}</details>`;
  const body = html`
    <h1>Economics</h1>
    ${notice}
    <p class="lede">${s.sentence}</p>

    <dl class="glance eco-glance" aria-label="The money, at a glance">
      ${tile('cash', 'In Stripe, ours', s.held, 'settled with the provider; not a bank balance')}
      ${tile('reserve', 'Held for tax', s.taxReserve, s.taxReserve.policy ? 'from the assumption you recorded' : 'no assumption recorded yet')}
      ${tile('reserve', 'Kept to keep running', s.operatingReserve, 'the floor you set')}
      ${tile('warn', 'Could be asked back', s.refundExposure, 'refund exposure on delivered work')}
      ${tile('owner', 'Yours to take', s.figure, s.figure.cents !== null && s.figure.cents < 0 ? 'more is spoken for than is held' : 'after everything already spoken for', ' yours')}
    </dl>

    <div class="know">
      <h2>The subtraction</h2>
      <dl class="facts money">
        ${line('In Stripe, ours', s.held)}
        ${line('Paid for, not delivered', s.obligations, true)}
        ${line('Could be asked back', s.refundExposure, true)}
        ${line('Held for tax', s.taxReserve, true)}
        ${line('Kept to keep running', s.operatingReserve, true)}
        ${line('Already authorised to spend', s.authorisedCapital, true)}
        <div class="mline total">
          <dt>Yours to take</dt>
          <dd>${fig(s.figure)}</dd>
        </div>
      </dl>
      ${owedToBuyers.length ? html`<h2>Owed to buyers</h2>
      <ul class="owed-to-buyers">${owedToBuyers.map((o) => html`<li><a href="/foundry/experiments/${o.experimentId}">${o.sentence}</a>${o.asksHim ? html` <strong>${o.asksHim}</strong>` : ''}</li>`)}</ul>` : ''}
      ${reasons([
    ['In Stripe, ours', s.held],
    ['Paid for, not delivered', s.obligations],
    ['Could be asked back', s.refundExposure],
    ['Held for tax', s.taxReserve],
    ['Kept to keep running', s.operatingReserve],
    ['Already authorised to spend', s.authorisedCapital],
    ['Yours to take', s.figure],
  ])}
    </div>

    <section class="panel trend eco-trend" aria-label="Money movement, thirty days">
      <header><h2>${mark('cash')}Movement <span class="dim">30 days</span></h2></header>
      ${spark.svg ? html`<div class="chart">${raw(spark.svg)}</div>` : ''}
      <p class="figures"><span class="up">+${dollars(inCents)} in</span><span class="down">−${dollars(outCents)} out</span>
        ${recent.length === 0 ? html`<span class="quiet">nothing has moved yet; the first row will be written by Stripe, not by me</span>`
    : spark.svg ? '' : html`<span class="quiet">${String(byDay.size)} ${byDay.size === 1 ? 'day' : 'days'} with movement — not yet a trend</span>`}</p>
    </section>

    <section class="panel ledger-panel" aria-label="The ledger">
      <header><h2>${mark('changed')}Economic events</h2><span class="dim">${ledger.length ? `${String(ledger.length)} newest, in the order the world put them` : ''}</span></header>
      ${ledger.length === 0
        ? html`<p class="quiet">Nothing yet. The first row will be written by Stripe, not by me.</p>`
        : html`<ul class="ledger">${ledger.map((e) => html`<li class="${e.direction}">
            ${mark(KIND_MARK(e))}
            <span class="what">${e.whatItIs}${e.quality === 'estimated' ? html` <span class="pill warn">estimated</span>` : ''}</span>
            <span class="amt">${e.direction === 'out' ? '−' : '+'}${dollars(e.amountCents)}</span>
            <span class="when"><time>${ago(e.occurredAt)}</time> · ${e.provider}${e.fromEvent ? ` event ${e.fromEvent}` : ` ${e.providerRef}`}</span>
            <details class="why-row"><summary class="quiet">why</summary><p class="quiet">${e.because}${e.assumption ? ` Assuming: ${e.assumption}.` : ''}</p></details>
          </li>`)}</ul>`}
    </section>

    <div class="inspect">
    ${fold('cannot', 'What I cannot tell you', `reached a bank: ${figureText(banked)}`, html`
      <p><strong>What has reached a bank: ${fig(banked)}.</strong> ${banked.because}</p>
      <p class="quiet">Gross charged, before Stripe took anything: ${figureText(gross)}. That number is
        not yours and is only here so the subtraction above can be checked against it.</p>`)}

    ${fold('sales', 'Every sale, and what was left of it', units.length ? `${String(units.length)} ${units.length === 1 ? 'sale' : 'sales'}` : 'none yet', units.length === 0
        ? html`<p class="quiet">Nothing has been sold. When something is, each sale appears here with
            what Stripe took out of it, so the margin is never guessed at from the price.</p>`
        : html`<ul class="sales">${units.map(({ row, view }) => html`<li>
            <b>${dollars(Number(row.amount_cents))}</b> ${String(row.status)}
            · Stripe took ${fig(view.providerFee)}
            · left ${fig(view.contribution)}
            ${view.contribution.cents === null
              ? html`<p class="quiet">${view.contribution.because}</p>` : ''}
          </li>`)}</ul>`)}

    ${fold('cost', 'What running this has cost', figureText(cost.total), html`
      <p><strong>${fig(cost.total)}</strong> ${cost.total.because}</p>
      <p class="quiet">Not part of the subtraction above. This money has already left, out of your own
        pocket rather than out of anything a buyer paid — subtracting it there would count it twice
        the moment you record having put money in.</p>
      ${cost.recent.length === 0 ? '' : html`<ul class="sales">${cost.recent.map((l) => html`<li>
          <b>${dollars(l.amountCents)}</b> on ${l.tool}${l.capability ? ` (${l.capability})` : ''}
          · ${l.source}${l.providerRef ? ` · receipt ${l.providerRef}` : ''}
          · ${l.at}
        </li>`)}</ul>`}`)}

    ${fold('set', 'What you can set', 'tax, the floor, money you moved', html`
      <h3>Tax</h3>
      <p class="quiet">An assumption of yours, applied to a measured basis, so money you may owe is
        not money you think you can take. It is never a filing, a return, or advice, and it will
        keep saying "estimated" wherever it appears.</p>
      <form class="inline" method="POST" action="/foundry/money/tax">
        <label class="sr" for="rate">Percentage to hold back</label>
        <input id="rate" name="rate" type="text" inputmode="decimal" placeholder="e.g. 30" />
        <label class="sr" for="basis">What it applies to</label>
        <select id="basis" name="basis">
          <option value="contribution">of contribution</option>
          <option value="gross_receipts">of gross receipts</option>
        </select>
        <label class="sr" for="taxsource">Where this comes from</label>
        <input id="taxsource" name="source" type="text" placeholder="Where this number comes from, in your words" />
        <button class="btn" type="submit">Record it</button>
      </form>

      <h3>The floor</h3>
      <p class="quiet">What stays in the account no matter what the arithmetic says.</p>
      <form class="inline" method="POST" action="/foundry/money/floor">
        <label class="sr" for="floor">Amount to keep</label>
        <input id="floor" name="amount" type="text" inputmode="decimal" placeholder="e.g. 500" />
        <label class="sr" for="floorwhy">Why</label>
        <input id="floorwhy" name="source" type="text" placeholder="Why that much" />
        <button class="btn" type="submit">Record it</button>
      </form>

      <h3>Money you moved</h3>
      <p class="quiet">A payout from this Stripe account mixes the land sales and AcreOS with this,
        so I will not read one as yours. What you actually moved, you can tell me, and then it is
        measured.</p>
      <form class="inline" method="POST" action="/foundry/money/moved">
        <label class="sr" for="amount">Amount</label>
        <input id="amount" name="amount" type="text" inputmode="decimal" placeholder="e.g. 250" />
        <label class="sr" for="direction">Direction</label>
        <select id="direction" name="direction">
          <option value="owner_distribution">I took out</option>
          <option value="owner_contribution">I put in</option>
        </select>
        <label class="sr" for="movedwhy">What it was</label>
        <input id="movedwhy" name="because" type="text" placeholder="What it was" />
        <button class="btn" type="submit">Record it</button>
      </form>`)}
    </div>`;
  return c.html(page('Economics', body, 'money', frame));
});

// ─── What the owner sets ─────────────────────────────────────────────────────

const back = (c: any, ok: string, err?: string) =>
  c.redirect(`/foundry/money?${err ? `error=${encodeURIComponent(err)}` : `done=${ok}`}`);

/** "30" and "30%" and "30.5" all mean the same thing to a person. */
function basisPoints(raw: string): number | null {
  const n = Number(String(raw).replace('%', '').trim());
  if (!Number.isFinite(n) || n < 0 || n > 100) return null;
  return Math.round(n * 100);
}

/** Dollars as typed, to whole cents. Refuses what it cannot read. */
function cents(raw: string): number | null {
  const n = Number(String(raw).replace(/[$,]/g, '').trim());
  if (!Number.isFinite(n) || n < 0) return null;
  return Math.round(n * 100);
}

moneyRoutes.post('/foundry/money/tax', requireInstitutionOwner(), async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return back(c, '', 'No owner on this request.');
  const form = await c.req.parseBody();
  const bps = basisPoints(String(form.rate ?? ''));
  const source = String(form.source ?? '').trim();
  if (bps === null) return back(c, '', 'That rate is not a percentage between 0 and 100.');
  if (!source) return back(c, '', 'An estimate has to say where it came from, or nobody can check it.');
  const basis = String(form.basis) === 'gross_receipts' ? 'gross_receipts' as const : 'contribution' as const;
  await setPolicy({
    founderId, kind: 'tax_reserve', rateBps: bps, basis, source,
    because: 'The owner recorded what he assumes he will owe, so that money is held back rather than counted as his.',
    setBy: 'owner',
  });
  return back(c, 'tax');
});

moneyRoutes.post('/foundry/money/floor', requireInstitutionOwner(), async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return back(c, '', 'No owner on this request.');
  const form = await c.req.parseBody();
  const amount = cents(String(form.amount ?? ''));
  const source = String(form.source ?? '').trim();
  if (amount === null) return back(c, '', 'That amount is not a number of dollars.');
  if (!source) return back(c, '', 'Say why that much, so the floor can be argued with later.');
  await setPolicy({
    founderId, kind: 'operating_reserve', amountCents: amount, source,
    because: 'The owner set a floor that stays in the account before anything is called his.',
    setBy: 'owner',
  });
  return back(c, 'floor');
});

moneyRoutes.post('/foundry/money/moved', requireInstitutionOwner(), async (c: any) => {
  const founderId = await founderOf(c);
  if (!founderId) return back(c, '', 'No owner on this request.');
  const form = await c.req.parseBody();
  const amount = cents(String(form.amount ?? ''));
  const because = String(form.because ?? '').trim();
  const direction = String(form.direction) === 'owner_contribution' ? 'owner_contribution' as const : 'owner_distribution' as const;
  if (amount === null || amount === 0) return back(c, '', 'That amount is not a number of dollars.');
  if (!because) return back(c, '', 'Say what the movement was, so the ledger reads as something rather than as an adjustment.');
  await record({
    founderId,
    kind: direction,
    amountCents: amount,
    occurredAt: new Date(),
    // NOT 'stripe'. The owner saying he moved money is a different kind of
    // evidence from Stripe saying so, and the provider column is what a
    // reconciler would use to ask the other side. `owner` is the other side.
    provider: 'owner',
    providerRef: `${direction}:${Date.now()}`,
    claimQuality: 'measured',
    evidenceMode: 'real',
    because,
  });
  return back(c, 'moved');
});
