// GENERATED by scripts/embed-proof-2.mjs from river/proof-2/*. Do not edit by hand.
export const LISTING_MD = `# Bid Decision Workbook for Small Contractors — Excel & Google Sheets

**Which bids are worth your time, and are you winning the ones you chase?**

One workbook for one decision: bid or don't. Log every bid you consider. The sheet works out, from your own history, how often you win from each lead source, what a bid is worth once you allow for that, and whether the hours it takes to bid are worth it. A summary shows win rate by lead source, why you lose, and how much submitted work is sitting against the capacity you set.

**What's in it**

- Bids sheet: one row per bid — client, scope, lead source, dates, estimated value, hours to bid, status, and why you lost. Drop-downs for lead source, status and loss reason.
- Computed for each bid: days to due, due flag, follow-up flag, the win rate used, expected value, bid cost, expected value per bidding hour, and a plain Signal: Worth it / Thin / Skip?
- Summary sheet: overall win rate, average value won vs lost, bidding hours per $1,000 won, submitted work against one month's capacity, win rate by lead source (with a chart), and a count of loss reasons.
- Settings sheet: your bidding hourly rate, monthly capacity, starting win-rate guess, and the lead sources and loss reasons you use. Yellow cells are yours to edit.
- Start-here sheet with a five-minute how-to and a legend.
- Example rows you delete before you start.

**What it is not**

It does not price or estimate a job, write proposals or invoices, schedule work, or track costs on a job. No macros, no add-ins, no account, nothing that phones home.

**Format and delivery**

Instant download after purchase: one .xlsx file. Opens in Excel 2010 or later, LibreOffice, and Google Sheets (File → Import → Upload → Replace spreadsheet; everything works unchanged). One-time purchase. Nothing recurs and nothing renews.

**Refunds**

If it is no use to you, you can have your money back. Message me through Etsy or use the refunds page at apexmicro.ai/refunds. No form and no time limit.

**Who made this**

Apex Micro is a small digital workshop in Massachusetts. This workbook was designed by Apex Micro with AI assistance in building the formulas and layout, and every formula was checked by hand before listing. Questions are welcome through Etsy messages and are answered by a person.

**Tags:** bid tracker, contractor spreadsheet, construction bid tracker, estimate log, win rate, small business template, excel template, google sheets template, contractor bid log, job pipeline, remodeling contractor, trade business
`;
export const HOW_TO_MD = `# Bid Decision Workbook — how to use it

Thank you for buying this. Here is everything you need, in five minutes.

## What it does

You log every bid you consider on the **Bids** sheet. The workbook works out, from your own history, how often you win from each lead source, what a bid is worth once you allow for that, and whether the hours it takes to bid are worth it. The **Summary** sheet shows win rate by lead source, why you lose, and how much submitted work is sitting against the capacity you set.

It does not price or estimate a job, write proposals or invoices, schedule work, or track costs on a job. One file for one decision: bid or don't.

## Set it up

1. Open **Settings**. Enter your bidding hourly rate (what an hour of your time spent bidding is worth to you), the monthly capacity you can take on in dollars, and a starting guess at your win rate for use until you have history. Edit the lead sources and loss reasons if yours are different. Yellow cells with blue text are yours; everything else is formulas.
2. Open **Bids**. Delete the grey EXAMPLE rows. Enter your own bids, one per row: client, scope in one line, lead source (drop-down), date received, due date, estimated value, hours it will take to bid, status (drop-down), and when it is submitted or decided, those dates. If you lost, pick a loss reason.
3. Read the **Signal** column before you spend hours on a bid. "Worth it", "Thin" or "Skip?" is a signal, not an instruction; you decide.
4. Read **Summary** once a month.

## How the Signal is worked out

- Win rate for a lead source is won divided by (won plus lost) from your own rows, once that source has at least the number of decided bids set on Settings (three by default). Before that it uses your overall win rate, and before you have any history it uses the starting guess on Settings.
- Expected value = estimated value × win rate.
- Bid cost = hours to bid × your rate.
- The Signal compares expected value per bidding hour with your rate: "Worth it" at or above the multiple you set on Settings, "Thin" at or above your rate, "Skip?" below it.

## Google Sheets

File → Import → Upload → choose this file → "Replace spreadsheet". Drop-downs, formulas and the chart carry over. Nothing needs re-entering.

## If something is wrong

Reply through Etsy messages and a person answers. If the workbook is no use to you, you can have your money back: message me through Etsy, or use the refunds page at apexmicro.ai/refunds. No form, no time limit, and you don't have to explain.

Apex Micro, a small digital workshop in Massachusetts. Designed with AI assistance in building the formulas and layout, checked by hand.
`;
export const PRIVACY_POLICY_MD = `# Apex Micro on Etsy — privacy policy

This policy covers what Apex Micro (Thomas Norton, Massachusetts) does with information when you buy from this Etsy shop. It sits alongside Etsy's own privacy policy, which governs Etsy's platform.

**What I receive.** When you buy, Etsy shows me your name, your Etsy username, and the email address Etsy provides for the order. For a digital download there is no shipping address.

**What I do with it.** I use it only to fulfil the order and to answer any message you send about it, through Etsy. I do not add you to a mailing list, I do not write to you about other products, and I do not share it with anyone.

**What I keep.** Nothing outside Etsy. Etsy keeps the order record on its platform under its own retention rules. My own records hold the order number and the amount, never your name or email.

**Your rights.** If you would like me to stop using your information for anything at all, message me through Etsy and I will. If you are in the EU or UK you have the rights the GDPR gives you, including access, correction and erasure of what I hold, which is the order number and amount above.

**Refunds and contact.** If the workbook is no use to you, you can have your money back: message me through Etsy. Questions are answered by a person.
`;
export const OWNER_ACTS_MD = `# Experiment 002 — the owner's acts

Only what Thomas literally must do himself. Foundry cannot perform any of these; each is an external boundary the institution does not cross on his behalf.

## Before the listing goes live

1. **Approve the experiment in Foundry** on its own page. That seals the design, sets the $25 allowance for 30 days, and records that Foundry contacts nobody and publishes nothing for this test.
2. **Open the Etsy shop as Apex Micro** under your own identity: Persona ID check and selfie, name, date of birth, address, partial SSN, and the one-time non-refundable $15 set-up fee.
3. **Attach one bank account in your name that holds only Apex Micro money** to Etsy Payments, and let the 5-day hold pass before listing. The name on the account must match your ID.
4. **Opt out of Offsite Ads** in Shop Manager → Settings → Offsite Ads. Do not start an Etsy Ads campaign. Do not enrol in Share & Save.
5. **Read Etsy's Fees & Payments Policy and Creativity Standards on screen.** This environment could not fetch them; the design rests on what Etsy's own pages said through search.
6. **Review the workbook, the how-to, the listing text with its disclosures, and the shop privacy policy.** Open the workbook in Excel or Google Sheets and confirm the example rows compute (the build environment could not produce cached values, so the file is set to calculate fully on open); then publish the listing at $14 with the AI-assistance disclosure in the description and the "Designed by" attribution set. Set the shop privacy policy text in the shop's policies.
7. **Paste the listing URL into Foundry** on the experiment page. That places the exposure and starts the 30-day clock.

## During the window

8. **Enter the venue's readings** on the experiment page at day 7, 14 and 30: impressions and position from Search Analytics, views, visits, favourites, orders, and the traffic-source split from Stats.
9. **Enter each order** as it appears: Etsy order number, date, gross amount, fees from the Etsy Payments statement. Enter any refund or case.

## At settlement

10. Nothing. Foundry settles by the sealed rule when the window closes, and records what changes next.
`;
export const WORKBOOK_FILE = 'bid-decision-workbook.xlsx';
export const WORKBOOK_SHA256 = 'cd6a2233c9af6bbad6903f6226fd2b293b7915e210e43d47311de3781b313817';
export const WORKBOOK_BYTES = 48303;
