#!/usr/bin/env node
// The Proof 2 listing text, how-to, shop privacy policy and owner acts live as
// Markdown under river/proof-2 for people to read, and are embedded here so the
// seed can run where only dist/ exists (production). The workbook itself is a
// binary the owner uploads to the venue by hand; the seed names it by its
// SHA-256 and size so the deliverable on record is exactly the file. Run after
// editing any of them; the test "the proof 2 seed carries the files it says it
// does" fails on drift.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const read = (f) => readFileSync(resolve(root, 'river/proof-2', f), 'utf8');
const lit = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
const workbook = readFileSync(resolve(root, 'river/proof-2/bid-decision-workbook.xlsx'));
const out = `// GENERATED by scripts/embed-proof-2.mjs from river/proof-2/*. Do not edit by hand.
export const LISTING_MD = ${lit(read('listing.md'))};
export const HOW_TO_MD = ${lit(read('how-to.md'))};
export const PRIVACY_POLICY_MD = ${lit(read('privacy-policy.md'))};
export const OWNER_ACTS_MD = ${lit(read('owner-acts.md'))};
export const WORKBOOK_FILE = 'bid-decision-workbook.xlsx';
export const WORKBOOK_SHA256 = '${createHash('sha256').update(workbook).digest('hex')}';
export const WORKBOOK_BYTES = ${workbook.length};
`;
writeFileSync(resolve(root, 'src/services/venture/proof-2-content.ts'), out);
console.log('embedded river/proof-2/{listing,how-to,privacy-policy,owner-acts}.md and the workbook digest');
