#!/usr/bin/env node
// The Proof 1 brief and offer text live as Markdown under river/proof-1 for
// people to read, and are embedded here so the seed can run where only dist/
// exists (production). Run after editing either file; the test
// "the proof 1 seed carries the files it says it does" fails on drift.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const read = (f) => readFileSync(resolve(root, 'river/proof-1', f), 'utf8');
const lit = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
const out = `// GENERATED by scripts/embed-proof-1.mjs from river/proof-1/*.md. Do not edit by hand.
export const BRIEF_MD = ${lit(read('brief.md'))};
export const OUTREACH_TEMPLATE_MD = ${lit(read('outreach-template.md'))};
`;
writeFileSync(resolve(root, 'src/services/venture/proof-1-content.ts'), out);
console.log('embedded river/proof-1/{brief,outreach-template}.md');
