#!/usr/bin/env bash
# =============================================================================
# FOUNDRY — Schema Snapshot
# Generates a deterministic plain-text snapshot of the SQLite schema after
# all migrations apply. Snapshot is committed to docs/db/schema.snapshot.sql
# and a CI job verifies it stays in sync with src/db/migrations/.
#
# Run locally after adding a migration:
#   bash scripts/schema-snapshot.sh
# Then commit the updated snapshot.
# =============================================================================

set -euo pipefail

SNAPSHOT="docs/db/schema.snapshot.sql"
TMPDB="$(mktemp -t foundry-schema.XXXXXX.db)"
trap 'rm -f "$TMPDB"' EXIT

# Apply migrations in lexical order. Tolerate "already exists" / "duplicate
# column" because some migrations are idempotent ALTERs.
# Apply all migrations. We tolerate per-statement errors because some of
# the older migrations have planner-level issues that the production
# runner swallows (see src/db/migrate.ts). The snapshot reflects the
# resulting schema regardless.
for f in src/db/migrations/*.sql; do
  sqlite3 "$TMPDB" < "$f" 2>/dev/null || true
done

mkdir -p "$(dirname "$SNAPSHOT")"

{
  echo "-- =========================================================================="
  echo "-- FOUNDRY — schema.snapshot.sql"
  echo "-- Auto-generated by scripts/schema-snapshot.sh"
  echo "-- DO NOT EDIT BY HAND. Re-run the script after adding a migration."
  echo "-- =========================================================================="
  echo ""
  # STATEMENT-ATOMIC, AND DETERMINISTIC WITHOUT SHREDDING ANYTHING.
  #
  # This was `.schema | sort`, which sorts the LINES of the dump. Every
  # multi-line CREATE TABLE and every trigger body was scattered across the
  # file in alphabetical order, so the committed snapshot — the thing a drift
  # check compares against and a human reads to understand the schema — was not
  # valid SQL and could not be applied to anything. Ordering by type and name
  # gives the same stable diff with each statement kept whole — ordered by what
  # depends on what, so the file can simply be applied to an empty database.
  sqlite3 "$TMPDB" "SELECT sql || ';' FROM sqlite_master
     WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
     ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'view' THEN 1
                        WHEN 'index' THEN 2 WHEN 'trigger' THEN 3 ELSE 4 END, name;"
} > "$SNAPSHOT"

echo "Wrote $SNAPSHOT"
