process.env.TURSO_DATABASE_URL = 'file::memory:';

import { Hono } from 'hono';
import { beforeAll, describe, expect, it } from 'vitest';
import { runMigrations } from '../../src/db/migrate.js';
import { query } from '../../src/db/client.js';
import { recordReconstructionClaim } from '../../src/services/institution/reconstruction.js';
import { earnResponsibilityUnderstanding } from '../../src/services/institution/responsibility-understanding.js';
import { setResponsibilityDisposition } from '../../src/services/institution/responsibility.js';
import { recordDevelopmentObservation, developmentEventType } from '../../src/services/institution/development-observation.js';
import { externalObservationEventType } from '../../src/services/institution/external-observation.js';
import {
  beginDevelopmentShadowing, resolveDevelopmentShadowing,
} from '../../src/services/institution/development-shadowing.js';
import {
  getMaterialShadowingExceptions, shadowExpectationPhrase,
} from '../../src/services/institution/responsibility-shadowing.js';

// ─── The founder decided, and Foundry kept reporting ─────────────────────────
//
// `deliberately_not_done` is a real decision with its own record, reason and
// evidence: the company is not doing this. `absence-summary` already honours it
// and keeps those responsibilities out of what needs the founder. The shadowing
// exceptions did not, so a responsibility the founder had explicitly retired
// went on producing "what differed while I watched" on the page they read every
// day — the institution still asking about a question its owner had closed.
//
// The comparison rows stay. Retiring a responsibility is not erasing what
// Foundry observed; it decides what belongs on the daily surface.

const P = 'rtd_product';
const OWNER = 'rtd_owner';
const CHECK = 'schema-snapshot-freshness';

const UNDERSTANDING: Array<[string, unknown]> = [
  ['purpose', 'Keep the committed schema snapshot in sync with the migrations'],
  ['desired_outcome', 'A migration and its snapshot always land together'],
  ['success_conditions', 'Regenerating the snapshot produces no diff'],
  ['operating_constraints', 'Generated artefact only; never hand-edited'],
  ['dependencies', 'The migration runner and the snapshot generator'],
  ['risks', 'A stale snapshot hides schema drift until an unrelated check fails'],
  ['systems', 'src/db/migrations and docs/db/schema.snapshot.sql'],
  ['failure_modes', 'Snapshot not regenerated after a migration is added'],
];

const RESP = 'rtd_resp';

async function setDisposition(disposition: 'active' | 'deliberately_not_done'): Promise<void> {
  await setResponsibilityDisposition({
    productId: P, responsibilityId: RESP, ownerId: OWNER, disposition,
    reason: disposition === 'active' ? 'we are doing this after all'
      : 'the snapshot is regenerated by CI now, so the company does not carry this',
    evidenceRef: 'signal_event:rtd_sig',
  });
}

beforeAll(async () => {
  await runMigrations();
  await query("INSERT INTO founders (id,clerk_user_id,email) VALUES (?,?,?)", [OWNER, 'rtd_clerk', 'rtd@example.com']);
  await query("INSERT INTO products (id,name,owner_id) VALUES (?,?,?)", [P, 'Retired Co', OWNER]);
  await query(`INSERT INTO signal_events (id,product_id,source,event_type,severity,payload_json,summary)
    VALUES ('rtd_sig',?,'repository','development_need_observed','medium','{}','Schema snapshot drifted from migrations')`, [P]);
  await query(`INSERT INTO institutional_responsibilities (id,product_id,title,capability,state)
    VALUES (?,?,'Keep the schema snapshot in sync with migrations','development','visible')`, [RESP, P]);
  for (const [predicate, value] of UNDERSTANDING) {
    await recordReconstructionClaim({
      productId: P, subject: `responsibility:${RESP}`, predicate, value,
      epistemicStatus: 'known', evidenceRefs: [{ kind: 'signal_event', id: 'rtd_sig' }],
      derivationMethod: 'observed repository reality', observedAt: new Date(),
    });
  }
  await earnResponsibilityUnderstanding(P, RESP);
  const claimId = await recordReconstructionClaim({
    productId: P, subject: `responsibility:${RESP}`, predicate: 'development_expectation',
    value: { check: CHECK, expected: 'passed' }, epistemicStatus: 'inferred', confidence: 0.8,
    evidenceRefs: [{ kind: 'signal_event', id: 'rtd_sig' }],
    derivationMethod: 'bounded expectation from observed repository reality', observedAt: new Date(),
  });
  const { expectationId } = await beginDevelopmentShadowing({
    productId: P, responsibilityId: RESP, expectedCheck: CHECK, expectedResult: 'passed',
    expectationClaimId: claimId, observationSourceSignalId: 'rtd_sig',
  });
  await query(
    "UPDATE responsibility_shadow_expectations SET created_at=datetime(created_at,'-10 seconds') WHERE id=?",
    [expectationId]);
  await recordDevelopmentObservation({
    productId: P, check: CHECK, result: 'failed', detail: 'a migration landed without a snapshot' });
  await resolveDevelopmentShadowing({ productId: P, expectationId });
});

async function letter(): Promise<string> {
  const { letterRoutes } = await import('../../src/routes/dashboard/letter.js');
  const app = new Hono();
  app.use('*', async (c, next) => {
    c.set('founder' as never, { id: OWNER, email: 'rtd@example.com', preferences: {} } as never);
    c.set('csrfToken' as never, 't' as never);
    await next();
  });
  app.route('/', letterRoutes as unknown as Hono);
  return (await app.request('/letter')).text();
}

describe('a responsibility the founder retired', () => {
  it('shows the deviation while the company is still doing it', async () => {
    expect((await getMaterialShadowingExceptions(P)).map((e) => e.classification)).toEqual(['deviated']);
    expect(await letter()).toContain('What differed while I watched');
  });

  it('stops reporting it once the founder decides the company is not doing it', async () => {
    await setDisposition('deliberately_not_done');
    expect(await getMaterialShadowingExceptions(P)).toEqual([]);
    expect(await letter()).not.toContain('What differed while I watched');
  });

  it('keeps the observation itself, which the decision was never about', async () => {
    expect((await query(
      "SELECT COUNT(*) n FROM responsibility_shadow_comparisons WHERE product_id=? AND classification='deviated'",
      [P])).rows[0]).toMatchObject({ n: 1 });
  });

  it('reports it again if the founder decides the company is doing it after all', async () => {
    await setDisposition('active');
    expect((await getMaterialShadowingExceptions(P)).map((e) => e.classification)).toEqual(['deviated']);
  });
});

describe('what Foundry expected, said in words', () => {
  // The phrase names the two identity families, and the constructors build
  // them. Two places knowing one format is the shape this repository treats as
  // a defect, so these are the comparison: if either constructor changes, the
  // phrase stops recognising it here rather than in front of a founder.
  it('reads back an identity either constructor can build', () => {
    expect(shadowExpectationPhrase(developmentEventType(CHECK, 'passed')))
      .toBe(`${CHECK} to report passed`);
    expect(shadowExpectationPhrase(externalObservationEventType('support_volume', 'fell')))
      .toBe('support_volume to have fallen');
    expect(shadowExpectationPhrase(externalObservationEventType('signups', 'rose')))
      .toBe('signups to have risen');
    expect(shadowExpectationPhrase(externalObservationEventType('churn', 'held')))
      .toBe('churn to have held steady');
  });

  it('prints an identity it does not recognise rather than inventing a sentence for it', () => {
    expect(shadowExpectationPhrase('something:else:entirely')).toBe('something:else:entirely');
    expect(shadowExpectationPhrase('support_reply_failed')).toBe('support_reply_failed');
    expect(shadowExpectationPhrase('development_verified:only_two')).toBe('development_verified:only_two');
  });

  it('does not print the internal identity to the founder', async () => {
    const page = await letter();
    expect(page).toContain(`${CHECK} to report passed`);
    expect(page).not.toContain('development_verified:');
  });
});
