import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { createClient } from '@libsql/client';
import { splitSqlStatements } from '../../src/db/migrate.js';

// =============================================================================
// THE COMMITTED SCHEMA IS A SCHEMA.
//
// docs/db/schema.snapshot.sql is what a drift check compares against and what a
// person reads to understand the shape of the institution. It was generated by
// piping sqlite3's .schema through `sort` — which sorts the LINES of the dump,
// so every multi-line CREATE TABLE and every trigger body was scattered across
// the file in alphabetical order.
//
// It looked like a schema. It could not be applied to anything, and nobody
// would have found that out until the day they needed to.
// =============================================================================

describe('docs/db/schema.snapshot.sql', () => {
  it('is SQL that actually applies to an empty database', async () => {
    const sql = readFileSync('docs/db/schema.snapshot.sql', 'utf8');
    const db = createClient({ url: 'file::memory:' });
    // Statement by statement, using the institution's own splitter — the one
    // that knows a trigger body contains semicolons.
    for (const stmt of splitSqlStatements(sql)) {
      await db.execute(stmt);
    }
    const tables = (await db.execute(
      "SELECT COUNT(*) AS n FROM sqlite_master WHERE type = 'table'"))
      .rows[0] as Record<string, unknown>;
    expect(Number(tables.n), 'the whole institution is in there')
      .toBeGreaterThan(250);
  });

  it('keeps every statement whole', () => {
    const sql = readFileSync('docs/db/schema.snapshot.sql', 'utf8');
    // A shredded dump has orphaned constraint lines at the start of a line —
    // the shape sorting produces. A whole one never does.
    const orphans = sql.split('\n')
      .filter((l) => /^\s*(CHECK|FOREIGN KEY|PRIMARY KEY|UNIQUE)\s*\(/.test(l)
        && !l.trimEnd().endsWith(','));
    expect(orphans.length, `orphaned constraint lines: ${orphans.slice(0, 3).join(' | ')}`)
      .toBeLessThan(200);
  });
});
